package main

func main() {
	err := run()
	exit(err)
}
